/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import { CenteringSection } from "../../../layouts/homePage.style";
import logo from "../../../public/images/testDog.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenteringSection>
        <Image alt="hi" src={logo} layout="responsive" />
      </CenteringSection>
    </div>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      // props for your component
      pet: "pet",
    },
  };
}
