// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-cH2NhQsRUZ6gizzcM73UoV54D7ES1YY',
    appId: '1:894557764172:web:edd0b38d861584ad0512e9',
    messagingSenderId: '894557764172',
    projectId: 'meebo-34a1a',
    authDomain: 'meebo-34a1a.firebaseapp.com',
    storageBucket: 'meebo-34a1a.appspot.com',
    measurementId: 'G-9DVKSY565D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5vUCpqjoGzN0tCLYAv-aun6SO2BS0btM',
    appId: '1:894557764172:android:c138b1d2c78f3ae90512e9',
    messagingSenderId: '894557764172',
    projectId: 'meebo-34a1a',
    storageBucket: 'meebo-34a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8HZ-lm0avEvE97n7y0NTRsLcxrVI3m8',
    appId: '1:894557764172:ios:47c51e829edd2a540512e9',
    messagingSenderId: '894557764172',
    projectId: 'meebo-34a1a',
    storageBucket: 'meebo-34a1a.appspot.com',
    iosClientId: '894557764172-h0v9fq2t1dh2egu1vcf7rjcp8tjbfjim.apps.googleusercontent.com',
    iosBundleId: 'com.example.meebo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8HZ-lm0avEvE97n7y0NTRsLcxrVI3m8',
    appId: '1:894557764172:ios:47c51e829edd2a540512e9',
    messagingSenderId: '894557764172',
    projectId: 'meebo-34a1a',
    storageBucket: 'meebo-34a1a.appspot.com',
    iosClientId: '894557764172-h0v9fq2t1dh2egu1vcf7rjcp8tjbfjim.apps.googleusercontent.com',
    iosBundleId: 'com.example.meebo',
  );
}
