/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  CenteringDiv,
  CenteringSection,
  InputButton,
  TextArea
} from "../layouts/homePage.style";
import { BootLegBody } from "../layouts/pet.style";
import logo from "../public/images/MeeboLogo.png";

export default function Home() {
  return (
    <BootLegBody>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenteringSection>
        <form
          onSubmit={(event) => {
            event.preventDefault();
          }}
        >
          <div>
            <label>
              <Image src={logo} layout="responsive" />
              {/* <InputButton>Username:</InputButton> */}
              <CenteringDiv>
                <TextArea type="text" />
              </CenteringDiv>
            </label>
          </div>

          <div>
            <label>
              {/* <InputButton>Password:</InputButton> */}
              <CenteringDiv>
                <
                <TextArea type="text" />
              </CenteringDiv>
            </label>
          </div>
          <div>
            <label>
              <InputButton>
                <CenteringDiv>
                  <Link href="/pet"> Next </Link>
                </CenteringDiv>
              </InputButton>
            </label>
          </div>
        </form>
      </CenteringSection>
    </BootLegBody>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      // props for your component
      pet: "pet",
    },
  };
}
