import Head from "next/head";
import Image from "next/image";
import {
  CenteringDiv,
  CenteringSection,
  InputButton,
  TextArea,
  WhiteSpace,
} from "../layouts/homePage.style";
import logo from "../public/images/logo.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenteringSection>
        <form
          onSubmit={(event) => {
            event.preventDefault();
          }}
        >
          <div>
            <label>
              <Image src={logo} layout="responsive" />
              <InputButton>User Name:</InputButton>
              <CenteringDiv>
                <TextArea type="text" />
              </CenteringDiv>
            </label>
          </div>

          <div>
            <label>
              <InputButton>Password:</InputButton>
              <CenteringDiv>
                <TextArea type="text" />
              </CenteringDiv>
            </label>
          </div>
          <WhiteSpace></WhiteSpace>
        </form>
        <div>
          <label>
            <InputButton>
              <a href="/pet">Next </a>
            </InputButton>
          </label>
        </div>
      </CenteringSection>
    </div>
  );
}
