/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import { Form } from "react-bootstrap";
import {
  CenteringDiv,
  CenteringSection,
  HomeScreen,
  InputButton,
  NextLabel,
} from "../layouts/homePage.style";
import logo from "../public/images/MeeboLogo.png";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <HomeScreen>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenteringSection>
        <form
          onSubmit={(event) => {
            event.preventDefault();
          }}
        >
          <div>
            <label>
              <Image src={logo} layout="responsive" />
              {/* <InputButton>Username:</InputButton> */}
              <CenteringDiv>
                <Form.Control
                  name="Username"
                  placeholder="Username"
                  className={styles.inputForm}
                />
              </CenteringDiv>
            </label>
          </div>

          <div>
            <label>
              {/* <InputButton>Password:</InputButton> */}
              <CenteringDiv>
                <Form.Control
                  name="Password"
                  placeholder="Password"
                  className={styles.inputForm}
                />
              </CenteringDiv>
            </label>
          </div>
          <div>
            <label>
              <InputButton>
                <CenteringDiv>
                  <Link href="/pet">
                    <NextLabel>Next</NextLabel>
                  </Link>
                </CenteringDiv>
              </InputButton>
            </label>
          </div>
        </form>
      </CenteringSection>
    </HomeScreen>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      // props for your component
      pet: "pet",
    },
  };
}
